# Generated by Django 2.1.15 on 2020-09-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0002_auto_20200904_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_allocation_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='device_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Mobile Name')),
                ('model_number', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('G', 'Gold'), ('BU', 'Blue'), ('BR', 'Brown'), ('GR', 'Grey'), ('RG', 'Rose Gold'), ('MB', 'Matte Black'), ('GW', 'Gold White'), ('GB', 'Grey Black'), ('OT', 'Other Colour')], max_length=2)),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Image')),
                ('extra_accessories', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchased', models.DateTimeField(verbose_name='Purchased Date')),
                ('device_type', models.CharField(choices=[('A', 'Android'), ('I', 'IOS'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/image', verbose_name='Image')),
                ('device_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.device_manager', verbose_name='Device Image')),
            ],
        ),
        migrations.CreateModel(
            name='request_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Requester Email Addresss')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Request Created Date')),
                ('assign_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.device_manager', verbose_name='Device Request or New Device')),
            ],
        ),
        migrations.AddField(
            model_name='device_allocation_manager',
            name='assign_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.device_manager', verbose_name='Assign Device Name'),
        ),
        migrations.AddField(
            model_name='device_allocation_manager',
            name='assign_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.TblEmployees', verbose_name='Assign Device Person Name'),
        ),
    ]
