# Generated by Django 2.1.15 on 2020-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_auto_20200907_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_manager',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Requester Email Address'),
        ),
    ]
