# Generated by Django 2.1.15 on 2020-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmsTblcountry',
            fields=[
                ('countryid', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'pms_tblcountry',
            },
        ),
        migrations.CreateModel(
            name='PmsTblcurency',
            fields=[
                ('curuncyid', models.AutoField(db_column='CuruncyID', primary_key=True, serialize=False)),
                ('curuncyname', models.TextField(blank=True, db_column='CuruncyName', null=True)),
            ],
            options={
                'db_table': 'pms_tblcurency',
            },
        ),
        migrations.CreateModel(
            name='PmsTbldepartment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('departmentname', models.TextField(blank=True, db_column='DepartmentName', null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'pms_tbldepartment',
            },
        ),
        migrations.CreateModel(
            name='PmsTblemployees',
            fields=[
                ('empid', models.AutoField(db_column='EmpID', primary_key=True, serialize=False)),
                ('empname', models.TextField(blank=True, db_column='EmpName', null=True)),
                ('roleid', models.IntegerField(blank=True, db_column='RoleID', null=True)),
                ('loginid', models.TextField(blank=True, db_column='LoginID', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('empcode', models.TextField(blank=True, db_column='EmpCode', null=True)),
            ],
            options={
                'db_table': 'pms_tblemployees',
            },
        ),
        migrations.CreateModel(
            name='PmsTblemployeetechnologies',
            fields=[
                ('etid', models.AutoField(db_column='ETID', primary_key=True, serialize=False)),
                ('empid', models.IntegerField(blank=True, db_column='EmpID', null=True)),
                ('techid', models.IntegerField(blank=True, db_column='TechID', null=True)),
            ],
            options={
                'db_table': 'pms_tblemployeetechnologies',
            },
        ),
        migrations.CreateModel(
            name='PmsTblflag',
            fields=[
                ('flagid', models.AutoField(db_column='FlagID', primary_key=True, serialize=False)),
                ('flagimagepath', models.TextField(blank=True, db_column='FlagImagePath', null=True)),
            ],
            options={
                'db_table': 'pms_tblflag',
            },
        ),
        migrations.CreateModel(
            name='PmsTblholidays',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('holidaydate', models.DateTimeField(blank=True, db_column='HolidayDate', null=True)),
                ('occasionname', models.CharField(blank=True, db_column='OccasionName', max_length=200, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='isActive', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('datemodified', models.DateTimeField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'pms_tblholidays',
            },
        ),
        migrations.CreateModel(
            name='PmsTbllockedresource',
            fields=[
                ('lid', models.BigAutoField(db_column='LID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('lockeddate', models.DateTimeField(blank=True, db_column='LockedDate', null=True)),
                ('lockedby', models.IntegerField(blank=True, db_column='LockedBy', null=True)),
                ('unlockeddate', models.DateTimeField(blank=True, db_column='UnlockedDate', null=True)),
                ('unlockedby', models.IntegerField(blank=True, db_column='UnlockedBy', null=True)),
            ],
            options={
                'db_table': 'pms_tbllockedresource',
            },
        ),
        migrations.CreateModel(
            name='PmsTblsettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='Modified', null=True)),
            ],
            options={
                'db_table': 'pms_tblsettings',
            },
        ),
        migrations.CreateModel(
            name='PmsTbltechnologies',
            fields=[
                ('techid', models.AutoField(db_column='TechID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'pms_tbltechnologies',
            },
        ),
        migrations.CreateModel(
            name='PmsTbluser',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('accountemail', models.TextField(blank=True, db_column='AccountEmail', null=True)),
                ('accountphone', models.TextField(blank=True, db_column='AccountPhone', null=True)),
                ('usertype', models.IntegerField(blank=True, db_column='UserType', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('usercode', models.IntegerField(blank=True, db_column='UserCode', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('deptid', models.IntegerField(blank=True, db_column='DeptID', null=True)),
                ('managerid', models.IntegerField(blank=True, db_column='ManagerID', null=True)),
                ('exempttimesheet', models.BooleanField(blank=True, db_column='ExemptTimesheet', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('uan', models.BigIntegerField(blank=True, db_column='UAN', null=True)),
                ('pan', models.TextField(blank=True, db_column='PAN', null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('imageurl', models.TextField(blank=True, db_column='ImageUrl', null=True)),
                ('timesheetcounter', models.IntegerField(db_column='TimesheetCounter')),
            ],
            options={
                'db_table': 'pms_tbluser',
            },
        ),
        migrations.CreateModel(
            name='PmsTbluserlog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('logindate', models.DateField(blank=True, db_column='LoginDate', null=True)),
                ('logintime', models.DateTimeField(blank=True, db_column='LoginTime', null=True)),
                ('logouttime', models.DateTimeField(blank=True, db_column='LogoutTime', null=True)),
                ('workingminutes', models.IntegerField(blank=True, db_column='WorkingMinutes', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'pms_tbluserlog',
            },
        ),
        migrations.CreateModel(
            name='PmsTblusertype',
            fields=[
                ('usertypeid', models.AutoField(db_column='UserTypeID', primary_key=True, serialize=False)),
                ('usertype', models.TextField(blank=True, db_column='UserType', null=True)),
            ],
            options={
                'db_table': 'pms_tblusertype',
            },
        ),
        migrations.CreateModel(
            name='TblCountry',
            fields=[
                ('countryid', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'tbl_Country',
            },
        ),
        migrations.CreateModel(
            name='TblCurency',
            fields=[
                ('curuncyid', models.AutoField(db_column='CuruncyID', primary_key=True, serialize=False)),
                ('curuncyname', models.TextField(blank=True, db_column='CuruncyName', null=True)),
            ],
            options={
                'db_table': 'tbl_Curency',
            },
        ),
        migrations.CreateModel(
            name='TblDepartment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('departmentname', models.TextField(blank=True, db_column='DepartmentName', null=True)),
                ('status', models.BooleanField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'tbl_Department',
            },
        ),
        migrations.CreateModel(
            name='TblEmployees',
            fields=[
                ('empid', models.AutoField(db_column='EmpID', primary_key=True, serialize=False)),
                ('empname', models.TextField(blank=True, db_column='EmpName', null=True)),
                ('roleid', models.IntegerField(blank=True, db_column='RoleID', null=True)),
                ('loginid', models.TextField(blank=True, db_column='LoginID', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('empcode', models.TextField(blank=True, db_column='EmpCode', null=True)),
            ],
            options={
                'db_table': 'tbl_Employees',
            },
        ),
        migrations.CreateModel(
            name='TblEmployeetechnologies',
            fields=[
                ('etid', models.AutoField(db_column='ETID', primary_key=True, serialize=False)),
                ('empid', models.IntegerField(blank=True, db_column='EmpID', null=True)),
                ('techid', models.IntegerField(blank=True, db_column='TechID', null=True)),
            ],
            options={
                'db_table': 'tbl_EmployeeTechnologies',
            },
        ),
        migrations.CreateModel(
            name='TblFlag',
            fields=[
                ('flagid', models.AutoField(db_column='FlagID', primary_key=True, serialize=False)),
                ('flagimagepath', models.TextField(blank=True, db_column='FlagImagePath', null=True)),
            ],
            options={
                'db_table': 'tbl_Flag',
            },
        ),
        migrations.CreateModel(
            name='TblHolidays',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('holidaydate', models.DateTimeField(blank=True, db_column='HolidayDate', null=True)),
                ('occasionname', models.CharField(blank=True, db_column='OccasionName', max_length=200, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='isActive', null=True)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('datemodified', models.DateTimeField(blank=True, db_column='DateModified', null=True)),
            ],
            options={
                'db_table': 'tbl_Holidays',
            },
        ),
        migrations.CreateModel(
            name='TblLockedresource',
            fields=[
                ('lid', models.BigAutoField(db_column='LID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('lockeddate', models.DateTimeField(blank=True, db_column='LockedDate', null=True)),
                ('lockedby', models.IntegerField(blank=True, db_column='LockedBy', null=True)),
                ('unlockeddate', models.DateTimeField(blank=True, db_column='UnlockedDate', null=True)),
                ('unlockedby', models.IntegerField(blank=True, db_column='UnlockedBy', null=True)),
            ],
            options={
                'db_table': 'tbl_LockedResource',
            },
        ),
        migrations.CreateModel(
            name='TblSettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='Created', null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='Modified', null=True)),
            ],
            options={
                'db_table': 'Tbl_Settings',
            },
        ),
        migrations.CreateModel(
            name='TblTechnologies',
            fields=[
                ('techid', models.AutoField(db_column='TechID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'tbl_Technologies',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('accountemail', models.TextField(blank=True, db_column='AccountEmail', null=True)),
                ('accountphone', models.TextField(blank=True, db_column='AccountPhone', null=True)),
                ('usertype', models.IntegerField(blank=True, db_column='UserType', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Deleted', null=True)),
                ('usercode', models.IntegerField(blank=True, db_column='UserCode', null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('deptid', models.IntegerField(blank=True, db_column='DeptID', null=True)),
                ('managerid', models.IntegerField(blank=True, db_column='ManagerID', null=True)),
                ('exempttimesheet', models.BooleanField(blank=True, db_column='ExemptTimesheet', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('uan', models.BigIntegerField(blank=True, db_column='UAN', null=True)),
                ('pan', models.TextField(blank=True, db_column='PAN', null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
                ('imageurl', models.TextField(blank=True, db_column='ImageUrl', null=True)),
                ('timesheetcounter', models.IntegerField(db_column='TimesheetCounter')),
            ],
            options={
                'db_table': 'tbl_User',
            },
        ),
        migrations.CreateModel(
            name='TblUserlog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('logindate', models.DateField(blank=True, db_column='LoginDate', null=True)),
                ('logintime', models.DateTimeField(blank=True, db_column='LoginTime', null=True)),
                ('logouttime', models.DateTimeField(blank=True, db_column='LogoutTime', null=True)),
                ('workingminutes', models.IntegerField(blank=True, db_column='WorkingMinutes', null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateTimeField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'tbl_UserLog',
            },
        ),
        migrations.CreateModel(
            name='TblUsertype',
            fields=[
                ('usertypeid', models.AutoField(db_column='UserTypeID', primary_key=True, serialize=False)),
                ('usertype', models.TextField(blank=True, db_column='UserType', null=True)),
            ],
            options={
                'db_table': 'tbl_UserType',
            },
        ),
    ]
